apiVersion: batch/v1
kind: Job
metadata:
  name: addjob02
spec:
  template:
    metadata:
      annotations:
        autoscaling.cast.ai/removal-disabled: "true"
        foo.bar.io/name: bar
    spec:
      containers:
      - name: busybox
        image: busybox:1.35
        command: ["sleep",  "3600"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: addcronjob02
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            foo.bar.io/name: bar
            autoscaling.cast.ai/removal-disabled: "true"
        spec:
          containers:
          - name: busybox
            image: busybox:1.35
            command: ["sleep",  "3600"]
          restartPolicy: OnFailure